### ISSUE TITLE
help

### ISSUE THREAD

**Issue by anhtlauncher** [sefirosweb/minecraftLegion#11]
![image](https://user-images.githubusercontent.com/99712037/228817775-bc344998-c2be-4ace-8045-7b3e0435b26c.png)
any solution?

**Comment by sefirosweb** [comment]
Depends how you implemented,

The bot is trying to connect to localhost, but mind if you are using docker must be connect to the docker or ip of server,

Also try to "stable" version example 1.18

**Comment by sefirosweb** [comment]
Try the new version

**Comment by quangei** [comment]
cool project sefirosweb

**Comment by sefirosweb** [comment]
plese open again ticket if you still have error
