### ISSUE TITLE
Fail to start docker image

### ISSUE THREAD

**Issue by AnonyBrave** [sefirosweb/minecraftLegion#13]
**minecraftLegion fail to start if line 10 & 11 exist or is not commented inside docker-compose.yml file**

![image](https://github.com/sefirosweb/minecraftLegion/assets/56361784/ed1a7440-9d38-4c07-9b27-2e119ac16b15)

![image](https://github.com/sefirosweb/minecraftLegion/assets/56361784/eb14eaa5-f517-431e-a7af-87d83d455956)

**But if line 10 & 11 does not exist  or is commented**

![image](https://github.com/sefirosweb/minecraftLegion/assets/56361784/55ba7470-bcac-480c-9989-a96154837831)

**minecraftLegion start correctly :**

![image](https://github.com/sefirosweb/minecraftLegion/assets/56361784/3baa33f9-31de-44f4-a863-1e23c79aef5b)
i'm running this on Debian 12 with docker-compose package from debian repository

**Comment by GarraBlanca2003** [comment]
it needs a boolean ,for me worked replacing true with 1
