### ISSUE TITLE
bot disconnect after being teleported

### ISSUE THREAD

**Issue by AnonyBrave** [sefirosweb/minecraftLegion#14]
I teleported a bot, and now the server kick the bot for invalid packet
I think that's because the bot think he is at his older position
![image](https://github.com/sefirosweb/minecraftLegion/assets/56361784/6b594ccf-1f09-482d-bf29-0bd17cd7cf9d)

**Comment by AnonyBrave** [comment]
I use bungeecord with multiple server, the fact that the bot need to connect to the hub server and after connect to the survival server may be the cause of this bug.

**Comment by sefirosweb** [comment]
this issue, is not issue from my bot, maybe of core of mineflayer or anti bots server
